### ISSUE TITLE
multiple lm75 

### ISSUE THREAD

**Issue by clopez73** [jeremycole/Temperature_LM75_Derived#2]
Hello, great work.
 Consider making support for multiple simultaneous devices in different directions i2c, it is especially useful with nodemcu.

something like this

lm75a (0xf4) // initialize first lm75 a0, a1, a2 to vcc
lm75b (0x48) // initialize second lm75 ...
Serial.print (temperatureA.readTemperatureC ());
Serial.print (temperatureB.readTemperatureC ());

a lot of thanks

**Comment by jeremycole** [comment]
Hello @clopez73!

This is actually already possible! You just need to initialize them with the I2C addresses:

    Generic_LM75 temperatureA(0xf4);
    Generic_LM75 temperatureA(0x48);

And then you can use them exactly as you said above:

    Serial.print (temperatureA.readTemperatureC ());
    Serial.print (temperatureB.readTemperatureC ());

I should create an example Arduino sketch for multiple sensors!

Regards,

Jeremy
