### ISSUE TITLE
Changing sensor resolution

### ISSUE THREAD

**Issue by AntaresAdroit** [jeremycole/Temperature_LM75_Derived#8]
I am trying to change the resolution my sensor (a TMP275) is using. I cannot find an example that shows how to do that and I am having trouble interpreting the source file to provide the right argument for the function.

I have the sensor declared:  

`TI_TMP275 temperature(B1001001);`

and that works fine; I get measurements with 0.5C resolution.

I have tried adding this line (just after `wire.begin(...)` in the code that works fine).:
`temperature.setResolution(3);`

Which throws the compilation error:
```
BasicUsage:18:30: error: invalid conversion from 'int' to 'Generic_LM75_9_to_12Bit_Compatible::Resolution' [-fpermissive]

   temperature.setResolution(3);

                              ^
```

I have also tried:
  `temperature.setResolution(Generic_LM75_9_to_12Bit_Compatible::Resolution::Resolution_12_bits);`

Which throws a more complicated error:
```
error: 'Generic_LM75_9_to_12Bit_Compatible::ConfigurationBits Resolution' is protected

     Resolution        = 5, // mask 0x60, length 2 bits

     ^

BasicUsage:18:65: error: within this context

   temperature.setResolution(Generic_LM75_9_to_12Bit_Compatible::Resolution::Resolution_12_bits);

                                                                 ^

BasicUsage:18:65: error: 'Generic_LM75_9_to_12Bit_Compatible::Resolution' is not a class, namespace, or enumeration

exit status 1
within this context
```

It might be clear to others with more C++ programming experience, but it is not clear to me how to provide the correct argument to the `temperature.setResolution();` function to change the resolution. Any help is appreciated.

**Comment by jeremycole** [comment]
Howdy! C++ has some interesting namespacing behaviors around `enum` that can make parsing apart errors fun. It's not just you. 😄 You should be able to set the resolution with the following, anywhere after the `Wire.begin()` call:

```c++
temperature.setResolution(TI_TMP275::Resolution_12_bits);
```

**Comment by AntaresAdroit** [comment]
I guess it makes sense that the enum just belongs to the class. Thanks!
